#A list of mod ids whose drawers should
#always be created, even if the mod is not present.
"force load" = []
#Set this to true to force all available mods to load.
"force all" = false
#A list of mod ids whose drawers should
#never be created, even if the mod is loaded.
disable = []

